### ISSUE TITLE
Getting this error

### ISSUE THREAD

**Issue by tahercoolguy** [aayusharora/GeneticAlgorithms#2]
As i am new to webpack . Can you please help me out of this 

npm run
Lifecycle scripts included in chrome-dino-game:
  start
    webpack-dev-server --mode development

available via `npm run-script`:
  build
    webpack --mode production

**Comment by DragonEmperorG** [comment]
This repository‘s ’scripts have only two remained. Check the package.json file.
![image](https://user-images.githubusercontent.com/24807062/48659519-43961e00-ea8d-11e8-907e-89812729d592.png)
You could call `npm run start` or `npm run build`

**Comment by tahercoolguy** [comment]
C:\wamp\www\dino-game\GeneticAlgorithms-master\part1\node_modules\webpack-cli\bin\config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\wamp\www\dino-game\GeneticAlgorithms-master\part1\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\wamp\www\dino-game\GeneticAlgorithms-master\part1\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\wamp\www\dino-game\GeneticAlgorithms-master\part1\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chrome-dino-game@1.0.0 build: `webpack --mode production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chrome-dino-game@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\hp\AppData\Roaming\npm-cache\_logs\2018-11-20T10_46_57_313Z-debug.log

Getting this error when running npm run start or npm run build

**Comment by aayusharora** [comment]
To build the web-pack,
you can run `npm build` and to start the server you can run `npm start`
@tahercoolguy
