### ISSUE TITLE
"npm  run start" and "npm run build" failed

### ISSUE THREAD

**Issue by DragonEmperorG** [aayusharora/GeneticAlgorithms#3]
![image](https://user-images.githubusercontent.com/24807062/48659567-f36b8b80-ea8d-11e8-836e-110b8a11599b.png)

**Comment by aayusharora** [comment]
@pratyush1687 Can you look into this?

**Comment by tahercoolguy** [comment]
Change your package.json 

    "webpack": "4.19.1",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^2.1.4",
    "webpack-merge": "^4.1.2",
    "webpack-dev-server": "^3.1.3"

I think there is some issue in webpack version

**Comment by pratyush1687** [comment]
yeah @tahercoolguy is right, the webpack versions should correspond to 
![image](https://user-images.githubusercontent.com/25077017/49922706-7e964080-fed7-11e8-9fc2-2d4a3c2b7c68.png)
